### ISSUE TITLE
Filtragem por agregação regional não funciona na API REST

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#100]
A pesquisas REST de "Resultados das Eleições por Cargo", o campo `agregacao_politica` é ignorado.

Observe que a indicação **API REST** na issue não necessariamente restringue o problema à API REST.

**Comment by elianalins** [comment]
Olá @rcarocha ,

tivemos uma alteração recente na nossa API Rest, o que você pode acompanhar por meio da nossa [documentação](https://github.com/Cepesp-Fgv/cepesp-rest). Veja este exemplo de consulta à Eleição de Deputados Federais, 2014, c/ agregação política Consolidado da Eleição (que devolve votos brancos e nulos, abstenções etc.):

Requisição:
`http://cepesp.io/api/consulta/athena/query?table=tse&cargo=6&anos=2014&agregacao_politica=4`

Esta requisição me devolve o ID **7182**, que utilizamos na consulta final: `cepesp.io/api/consulta/athena/result?id=7182&ignore_version=true`.

Agradecemos sua contribuição. Espero que tenha ajudado. 
Ficamos à disposição, Equipe Cepespdata/FGV
