### ISSUE TITLE
Filtragem de dados de candidatos por título não funciona na API RESP

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#101]
Aparentemente, a pesquisa com filtragem de dados de candidatos por título de eleitor não funciona na API REST, em uma consulta por resultado de eleição.

Observe que a indicação **API REST** na issue não necessariamente restringue o problema à API REST.

**Comment by elianalins** [comment]
Olá @rcarocha ,

Com a nossa [nova API Rest](https://github.com/Cepesp-Fgv/cepesp-rest), é possível realizar o filtro por título da seguinte forma

Faça a consulta inicial `/api/consulta/athena/query?table=<TABELA>&<ARGUMENTOS>` inserindo o argumento `&filters[<COLUNA>]=<VALOR>`. Por exemplo, p/ filtrar título de eleitor do Eduardo Cunha, eleito Dep. Federal pelo RJ em 2014, fazemos a requisição:

`cepesp.io//api/consulta/athena/query?table=tse&cargo=6&anos=2014&filters[NUM_TITULO_ELEITORAL_CANDIDATO]=010915780388`

De onde extraímos o ID **7194** que usamos na consulta final:

`cepesp.io//api/consulta/athena/result?id=7194&ignore_version=true`.

Ficamos à disposição,
Equipe Cepespdata/FGV
