### ISSUE TITLE
Número de votos por partido inconsistente em diferentes interfaces de consulta (API REST).

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#103]
Os número de votos por partido para alguns partidos não estão sendo computados ao pesquisar o resultado agregado de uma eleição. O problema foi verificado na seguinte situação:

1. Resultados das eleições por cargo
2. Deputado Federal
3. Agregação Regional = Estado
4. Agregação Política = Candidato

Nessa situação, a API tem retornado os votos por partido como votos por candidato, sendo que o candidato possui título eleitoral "#NULO#". Utilizamos na aplicação esse método para coletar os votos por partido.

**Problema**: Os votos de alguns partidos não são coletados. Para a situação mencionada e para o estado de GO, percebi que não foram coletados os votos do PT e do PSOL. Os votos desses partidos também não são coletados quando realizados uma **pesquisa com agregação por coligação**.

Entretanto, a coleta dos mesmos dados utilizando a agregação por partido político funciona, o que leva a crer que o problema é que API está ignorando nas demais pesquisas os partidos que constam como PARTIDOS ISOLADOS.

Observe que a indicação **API REST** na issue não necessariamente restringue o problema à API REST.

Relacionado com a issue #53 .

**Comment by rcarocha** [comment]
Observe que esse problema foi verificado no contexto dos dados da eleição de 2014 e nos demais o problema pode ser mais ou menos evidente.

**Comment by elianalins** [comment]
Olá, @rcarocha ,

Este problema foi resolvido. No tocante à consultas que você mencionou, os votos na legenda do PT em GO estão disponíveis por meio [desta consulta](http://cepespdata.io/consulta/tse?cargo=6&agregacao_regional=2&agregacao_politica=2&anos%5B%5D=2014&uf_filter=&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=UF&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS), e os do PSOL, no mesmo estado, [nesta consulta](http://cepespdata.io/consulta/tse?cargo=6&agregacao_regional=2&agregacao_politica=2&anos%5B%5D=2014&uf_filter=&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=UF&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS) -- em ambos os casos p/ o ano de 2014.

Ficamos à disposição, Equipe Cepespdata
