### ISSUE TITLE
Base de coligações retorna algumas com partido igual a "#NE#"

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#105]
Uma pesquisa por coligações algumas com partido igual a "#NE#". Por exemplo:

```
6,	1,	JUNTOS POR UM ESPÍRITO SANTO MAIS FORTE,	#NE#,	DEPUTADO FEDERAL,	2014,	PRP / PEN,	Espírito Santo,	ES,	50672
```

O contexto da pesquisa está indicado na resposta.

**Comment by elianalins** [comment]
Olá @rcarocha , boa tarde.

Este `#NE#` se refere à silga da coligação e não à sigla do partido. PEN e PRP são os dois partidos da coligação JUNTOS POR UM ESPÍRITO SANTO MAIS FORTE. Veja você mesmo a consulta [aqui](http://cepespdata.io/consulta/legendas?cargo=6&anos%5B%5D=2014&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=SIGLA_UE&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=TIPO_LEGENDA&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=SIGLA_COLIGACAO&c%5B%5D=NOME_COLIGACAO&c%5B%5D=COMPOSICAO_COLIGACAO), de onde fiz o download da planilha anexa a seguir: [LEGENDAS_DEPUTADO_FEDERAL_2014.zip](https://github.com/Cepesp-Fgv/tse-dados/files/3393613/LEGENDAS_DEPUTADO_FEDERAL_2014.zip).

Ficamos à disposição,

Abraços, Equipe Cepespdata
