### ISSUE TITLE
Consultas CEPESP por votos usando agregação por município não retornam votos em legenda (API REST).

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#106]
As consultas CEPESP.io de votos na **agregação município** não incluem os votos em legenda (aqueles indicados com título de eleitor igual a `"#NULO#"`), computando apenas os votos nos candidatos que pertencem aos partidos como votos em legenda.

Exemplo de consulta:

```
http://cepesp.io/consulta/tse?cargo=6&agregacao_regional=6&agregacao_politica=2&anos%5B%5D=2014&uf_filter=GO&mun_filter=
```

Nas demais agregação, tais votos aparecem como votos no candidato com `numero=num_partido` e com título de eleitor igual a `"#NULO#"`.

A pesquisa por coligaçao (usando esse tipo de agregação) também só computa os votos dos candidatos, deixando as legendas de lado.

Observe que a indicação **API REST** na issue não necessariamente restringue o problema à API REST.

**Comment by elianalins** [comment]
Boa tarde, @rcarocha ,

Este problema parece estar resolvido. A consulta aos votos na legenda p/ as eleições dos Dep. Federais de 2014, no estado de GO, agregação regional município, podem ser acessadas via API Rest da seguinte forma:

`cepesp.io/api/consulta/athena/query?table=tse&cargo=6&anos=2014&agregacao_politica=2&agregacao_regional=6&filters[UF]=GO`

Desta consulta, obtemos o id **7281**, que usamos p/ baixar o banco via:

`cepesp.io/api/consulta/athena/result?id=7281&ignore_version=true`

Filtrando os dados do CSV resultante (ver no ZIP anexo) p/ `NUMERO_CANDIDATO<100`, temos os votos na legenda, conforme o arquivo XLSX (também no ZIP anexo:
[TSE_DEPFED_2014_GO.zip](https://github.com/Cepesp-Fgv/tse-dados/files/3412073/TSE_DEPFED_2014_GO.zip) ).

Ficamos à disposição,
Equipe Cepespdata/FGV
