### ISSUE TITLE
Pesquisa de dados de eleição por município, utilizando filtragem por COD_MUN_IBGE extremamente lentas (API REST).

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#107]
Pesquisa de dados de eleição por município, utilizando filtragem por `COD_MUN_IBGE` extremamente lentas, demorando de 15s até mais de 1min (houve caso de 4min sem resultado). Aparentemente, não há motivo para esse atraso, já que utilizamos pesquisas filtradas por código de município.

Esse problema é bastante **CRÍTICO**. Para se ter uma idéia, deixei um programa por mais de 12 horas, repetindo as consultas com falhas, e ainda assim ele não foi capaz de realizar uma pesquisa com todos os municípios.

Observe que a indicação **API REST** na issue não necessariamente restringue o problema à API REST.

**Comment by elianalins** [comment]
Boa tarde, @rcarocha . Houve uma atualização do [nosso site](http://cepespdata.io/) e da nossa [API Rest](https://github.com/Cepesp-Fgv/cepesp-rest) desde que você abriu este Issue #107. Assim, convidamos você a dar uma olhada e explorar mais uma vez os dados do Cepespdata/FGV. Não hesite em nos contactar caso a instabilidade ou a velocidade continue sendo um empecilho à utilização dos nossos dados.

Sabemos que a velocidade tem sido uma das maiores limitações do nosso sistema e já estamos trabalhando nisso.

Agradecemos a contribuição e ficamos à disposição,
Equipe Cepespdata/FGV
