### ISSUE TITLE
Dados deputados estaduais 2002 nao baixan em csv

### ISSUE THREAD

**Issue by kbaragwa** [Cepesp-Fgv/tse-dados#108]

**Comment by elianalins** [comment]
Olá @kbaragwa ,

Obrigada pelo comentário. Esta função já foi corrigida. Veja [aqui](http://cepespdata.io/consulta/tse?cargo=7&agregacao_regional=0&agregacao_politica=2&anos%5B%5D=2002&uf_filter=&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=SIGLA_UE&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS) a consulta a Dep. Estaduais 2002, com a função download de csv funcionando. 

Sempre à disposição, Equipe Cepespdata
