### ISSUE TITLE
Dados de candidato a prefeito 2012  com possível erro de atribuição.. primeiras filas reportan NE

### ISSUE THREAD

**Issue by kbaragwa** [Cepesp-Fgv/tse-dados#109]

**Comment by elianalins** [comment]
Olá @kbaragwa , 
Este problema já foi resolvido. Veja esta consulta funcionando [aqui](http://cepespdata.io/consulta/candidatos?cargo=11&anos%5B%5D=2012&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=SIGLA_UE&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NOME_URNA_CANDIDATO&c%5B%5D=DESCRICAO_SEXO&c%5B%5D=DESC_SIT_TOT_TURNO)

Sempre à disposição, Equipe Cepespdata
