### ISSUE TITLE
Problema com CSV

### ISSUE THREAD

**Issue by claudiacerqn** [Cepesp-Fgv/tse-dados#110]
Quando executada uma query na aba "Eleições por Cargo", cepespdata retorna os resultados corretamente, mas isto não ocorre quando faço download do csv - a planilha vem em branco, independentemente do tipo de consulta efetuada.

**Comment by elianalins** [comment]
Boa tarde, @claudiacerqn. A função de download do csv já está funcionando normalmente no nosso [site](http://cepespdata.io/consulta/tse). 

Abraços, Equipe Cepespdata
