### ISSUE TITLE
Consulta por seção eleitoral traz zero resultados

### ISSUE THREAD

**Issue by bramatti** [Cepesp-Fgv/tse-dados#111]
Consultei resultados da eleição presidencial de 2014 por seção eleitoral, nas UFs SP e SC. Resultado: 

Showing 0 to 0 of 0 entries (filtered from 5,071,959 total entries)

**Comment by elianalins** [comment]
Olá @bramatti , 
Essas consultas foram corrigidas e já estão disponíveis normalmente para [SP](http://cepespdata.io/consulta/tse?cargo=1&agregacao_regional=9&agregacao_politica=2&anos%5B%5D=2014&uf_filter=SP&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=NUM_ZONA&c%5B%5D=NUM_SECAO&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS) e [SC](http://cepespdata.io/consulta/tse?cargo=1&agregacao_regional=9&agregacao_politica=2&anos%5B%5D=2014&uf_filter=SC&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=NUM_ZONA&c%5B%5D=NUM_SECAO&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS).

Abraços, Equipe Cepespdata
