### ISSUE TITLE
Consulda de "Resultados de Eleição" não retorna resultados

### ISSUE THREAD

**Issue by RCCSilva** [Cepesp-Fgv/tse-dados#112]
Em "Resultados de Eleição", para o cargo "Deputado Estadual", por agregação regional por "Votação Seção" no ano de 2014 para o estado de SP, o site não retorna resultados.

O site fica apenas com uma página "Processing...".

**Comment by elianalins** [comment]
Bom dia, @RCCSilva 

Esta consulta já está funcionando normalmente. Veja a consulta [aqui](http://cepespdata.io/consulta/tse?cargo=7&agregacao_regional=9&agregacao_politica=2&anos%5B%5D=2018&uf_filter=SP&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=NUM_ZONA&c%5B%5D=NUM_SECAO&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS).

Abraços, Equipe Cepespdata
