### ISSUE TITLE
Mensagem de erro em consulta de deputados estaduais

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#114]
Ao fazer uma requisição sobre deputados estaduais e apareceu a seguinte mensagem: 
DataTables warning: table id=query-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
A consulta foi essa aqui: http://cepesp.io/consulta/tse?cargo=7&agregacao_regional=6&agregacao_politica=1&anos%5B%5D=2014&anos%5B%5D=2010&anos%5B%5D=2006&anos%5B%5D=2002&anos%5B%5D=1998&uf_filter=&mun_filter=&brancos=1&nulos=1

**Comment by elianalins** [comment]
Bom dia, @laramesquita. Este erro foi resolvido. 
Abraços, Equipe Cepespdata
