### ISSUE TITLE
votação duplicada na eleição presidencial de 2006, 2010 e 2014

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#115]
na requisição consulta eleição por cargo, agregação candidato e município, eleições de 1998, 2002, 2006, 2010 e 2014 os votos estão duplicados para as três últimas eleições.

**Comment by elianalins** [comment]
Bom dia, @laramesquita,

Issue testado na nossa API R e no site; problema resolvido.

Abraços, Equipe Cepespdata
