### ISSUE TITLE
Problemas baixando vereador>votação seção>2012>SP

### ISSUE THREAD

**Issue by lucarno** [Cepesp-Fgv/tse-dados#116]
Ao tentar baixar pelo site, encontro:
> DataTables warning: table id=query-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Usando `cepespR` encontro o seguinte erro:

> Error: 'Internal Server Error' does not exist in current working directory.

Consegui baixar os dados para os outros estados, embora alguns tenha somente conseguido depois de algumas tentativas.

**Comment by elianalins** [comment]
Olá, @lucarno, 
esta consulta já está disponível normalmente. 

Abraços, Equipe Cepespdata
