### ISSUE TITLE
Usabilidade do CEPESP Data

### ISSUE THREAD

**Issue by gabrielacaesar** [Cepesp-Fgv/tse-dados#117]
Oi, tudo bem?

Queria fazer uma sugestão para o CEPESP Data. Nas colunas que informam números, como a quantidade de votos, acredito que seria melhor se a formação fosse 195.110 (e não 195110). Ou 666.199 (e não 666199). Como são muitos números, esse ponto ajuda na leitura.

Outra questão: na consulta "RESULTADOS DAS ELEIÇÕES POR CARGO", não temos uma coluna que indica se o candidato foi eleito, ficou como suplente ou não foi eleito, certo?

**Comment by elianalins** [comment]
Olá, Gabriela. Como vai? 

Fizemos uma alteração recente no layout do nosso site e nas colunas default de cada consulta. A coluna DESC_SIT_TOT_TURNO que aparece na consulta default da consulta "RESULTADOS DAS ELEIÇÕES POR CARGO" devolve o Situação de Totalização do Turno (Suplente, Eleito, Não Eleito). Veja um exemplo na captura de tela abaixo.

Espero que ajude. 

Abraços, Equipe Cepespdata
![Screenshot from 2019-07-11 16-38-06](https://user-images.githubusercontent.com/47109522/61080003-74e7a380-a3fa-11e9-87c1-8aad7cf5a0e0.png)
