### ISSUE TITLE
problemas baixando consolidado eleições prefeitos

### ISSUE THREAD

**Issue by araujosvictor** [Cepesp-Fgv/tse-dados#120]
Prezados da equipe do CEPESP,
          a consulta não retorna o resultado quando peço o "consolidado das eleições" nas disputas para prefeito das eleições dos anos de 2008 e 2016. Para os outros anos (2000, 2004 e 2012) funciona normalmente. A mensagem de erro que aparece é a seguinte: "Ops! Ocorreu um problema com a sua consulta...Tente novamente mais tarde".

Agradeço desde já pela atenção. Aproveito para agradecer pelo trabalho incrível que vocês têm feito na organização dos dados do TSE. Trabalho super profissional e de qualidade. 

Att,

  Victor Araújo

**Comment by Cepesp-Fgv** [comment]
Olá, @araujosvictor,

Já identificamos o problema e estamos corrigindo. 
Enviaremos a correção assim que possível.

**Comment by elianalins** [comment]
Olá @araujosvictor ,

Esta consulta parece estar funcionando normalmente. Veja [aqui](http://cepespdata.io/consulta/tse?cargo=11&agregacao_regional=6&agregacao_politica=2&anos%5B%5D=2016&anos%5B%5D=2008&uf_filter=&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=COD_MUN_TSE&c%5B%5D=COD_MUN_IBGE&c%5B%5D=NOME_MUNICIPIO&c%5B%5D=UF&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS). Não hesite em nos contactar novamente caso encontre problema semelhante. 

Agradecemos sua contribuição e ficamos à disposição,
Equipe Cepespdata/FGV
