### ISSUE TITLE
Ordem dos Partidos na consulta de Filiados

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#121]
Caros, tudo bem?

Meu issue é mais uma sugestão do que um erro. Quando vou consultar a relação de filiados, o nome dos partidos estão ordenados de acordo com seu número. Isso causa confusão e demora para o usuário. Eu, por exemplo, demorei para encontrar a Rede. Se na barra de rolagem, os nomes estivessem em ordem alfabética resolveria o problema.

**Comment by elianalins** [comment]
Bom dia, @atrfisch. Obrigada pela sugestão!

**Comment by luizgabriel** [comment]
Feito.
