### ISSUE TITLE
Alterações no site Cepespdata/FGV

### ISSUE THREAD

**Issue by elianalins** [Cepesp-Fgv/tse-dados#123]
Boa noite, pessoal. Precisamos realizar algumas alterações no site até segunda-feira que vem, conforme conversamos na reunião do Cepespdata/FGV na última quarta-feira. Organizei as alterações no seguinte [documento](https://docs.google.com/document/d/1_vTJ8Lj9KWkilPJ5AWokLZ9hlurrKhJlqpI4ktEepNY/edit?usp=sharing).

As documentações p/ inserir no site seguem anexas ao issue ([arquivo ZIP](https://github.com/Cepesp-Fgv/tse-dados/files/3488272/atualizacao_site_20190808.zip)).

Abraços, Eliana

**Comment by abraaobarros** [comment]
Podemos fechar esse?

**Comment by elianalins** [comment]
Sim, claro!
