### ISSUE TITLE
alerta para consulta/download superior a 100 mil linhas

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#135]
é preciso incluir um alerta, para os usuários parece que simplesmente o sistema parou de responder

**Passos para reproduzir**
Passos para reproduzir o problema:
1. Navegue para '...'
2. Clique em '....'
3. Dê scroll até '....'
4. Digite 'abc' em '...'
5. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Comportamento observado**
Uma descrição clara e concisa do que realmente aconteceu.

**Screenshots**
Se aplicável, adicione screenshots para melhor explicar o problema.

**Informações do dispositivo:**
 - Dispositivo: [e.g. iPhone6]
 - Versão do SO: [e.g. iOS8.1]

**Contexto adicional**
Adicione mais qualquer outro contexto sobre o problema aqui.

**Comment by abraaobarros** [comment]
Atualizamos o site com um alerta no final das páginas consultas.
<img width="1164" alt="Screen Shot 2020-08-20 at 13 28 14" src="https://user-images.githubusercontent.com/1097909/90799049-18d39c00-e2e9-11ea-935a-fb870dfdc597.png">
