### ISSUE TITLE
Traduzir as colunas do TSE para ingles

### ISSUE THREAD

**Issue by abraaobarros** [Cepesp-Fgv/tse-dados#19]
São essas:
'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UE',
            'DESCRICAO_UE',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'NOME_CANDIDATO',
            'SEQUENCIAL_CANDIDATO',
            'NUMERO_CANDIDATO',
            'CPF_CANDIDATO',
            'NOME_URNA_CANDIDATO',
            'COD_SITUACAO_CANDIDATURA',
            'DES_SITUACAO_CANDIDATURA',
            'NUMERO_PARTIDO',
            'SIGLA_PARTIDO',
            'NOME_PARTIDO',
            'CODIGO_LEGENDA',
            'SIGLA_LEGENDA',
            'COMPOSICAO_LEGENDA',
            'NOME_LEGENDA',
            'CODIGO_OCUPACAO',
            'DESCRICAO_OCUPACAO',
            'DATA_NASCIMENTO',
            'NUM_TITULO_ELEITORAL_CANDIDATO',
            'IDADE_DATA_ELEICAO',
            'CODIGO_SEXO',
            'DESCRICAO_SEXO',
            'COD_GRAU_INSTRUCAO',
            'DESCRICAO_GRAU_INSTRUCAO',
            'CODIGO_ESTADO_CIVIL',
            'DESCRICAO_ESTADO_CIVIL',
            'CODIGO_COR_RACA',
            'DESCRICAO_COR_RACA',
            'CODIGO_NACIONALIDADE',
            'DESCRICAO_NACIONALIDADE',
            'SIGLA_UF_NASCIMENTO',
            'CODIGO_MUNICIPIO_NASCIMENTO',
            'NOME_MUNICIPIO_NASCIMENTO',
            'DESPESA_MAX_CAMPANHA',
            'COD_SIT_TOT_TURNO',
            'DESC_SIT_TOT_TURNO',
            'NM_EMAIL',
            'TIPO_LEGENDA',
            'SIGLA_COLIGACAO',
            'NOME_COLIGACAO',
            'COMPOSICAO_COLIGACAO',
            'SEQUENCIA_COLIGACAO',
            'CODIGO_MACRO',
            'NOME_MACRO',
            'UF',
            'NOME_UF',
            'CODIGO_MESO',
            'NOME_MESO',
            'CODIGO_MICRO',
            'NOME_MICRO',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUM_ZONA',
            'QTDE_VOTOS'

**Comment by atrfisch** [comment]
Caros, segue a tradução
---

'ANO_ELEICAO', - YEAR_ELECTION
'NUM_TURNO',  - ROUND_NUM
'DESCRICAO_ELEICAO', - ELECTION_DESCRIPTION
'SIGLA_UE', - ELECTORAL_UNIT_ABBREVIATION
'DESCRICAO_UE', ELECTORAL_UNIT_DESCRIPTION
'CODIGO_CARGO', - POSITION_CODE
'DESCRICAO_CARGO', - POSITION_DESCRIPTION
'NOME_CANDIDATO', - CANDIDATE_NAME
'SEQUENCIAL_CANDIDATO', - CANDIDATE_SEQUENTIAL
'NUMERO_CANDIDATO', - CANDIDATE_NUMBER
'CPF_CANDIDATO', CANDIDATE_CPF
'NOME_URNA_CANDIDATO', - CANDIDATE_BALLOT_NAME
'COD_SITUACAO_CANDIDATURA', - CANDIDATE_SITUATION_CODE
'DES_SITUACAO_CANDIDATURA', - CANDIDATE_SITUATION_DESC
'NUMERO_PARTIDO', - PARTY_NUMBER
'SIGLA_PARTIDO', - PARTY_ABBREVIATION
'NOME_PARTIDO', - PARTY_NAME
'CODIGO_LEGENDA',  - PARTY_LABEL_CODE
'SIGLA_LEGENDA', - PARTY_LABEL_ABBREVIATION
'COMPOSICAO_LEGENDA', - PARTY_LABEL_COMPOSITION
'NOME_LEGENDA', - PARTY_LABEL_NAME
'CODIGO_OCUPACAO', - CANDIDATE_OCCUPATION_CODE
'DESCRICAO_OCUPACAO', - CANDIDATE_OCCUPATION_DESC
'DATA_NASCIMENTO', - DATE_OF_BIRTH
'NUM_TITULO_ELEITORAL_CANDIDATO', - CANDIDATE_ELECTORAL_ID
'IDADE_DATA_ELEICAO', - CANDIDATE_AGE
'CODIGO_SEXO', - GENDER_CODE
'DESCRICAO_SEXO', - GENDER_DESCRIPTION
'COD_GRAU_INSTRUCAO', - CANDIDATE_EDUCATION_CODE
'DESCRICAO_GRAU_INSTRUCAO', - CANDIDATE_EDUCATION_DESCRIPTION
'CODIGO_ESTADO_CIVIL', - MARITAL_STATUS_CODE
'DESCRICAO_ESTADO_CIVIL', - MARITAL_STATUS_DESCRIPTION
'CODIGO_COR_RACA', - RACE_CODE
'DESCRICAO_COR_RACA', - RACE_DESCRIPTION
'CODIGO_NACIONALIDADE', - NATIONALITY_CODE
'DESCRICAO_NACIONALIDADE', - NATIONALITY_DESCRIPTION
'SIGLA_UF_NASCIMENTO', - BIRTH_STATE_ABBREVIATION
'CODIGO_MUNICIPIO_NASCIMENTO', - BIRTH_MUNICIPALITY_CODE
'NOME_MUNICIPIO_NASCIMENTO', - BIRTH_MUNICIPALITY_NAME
'DESPESA_MAX_CAMPANHA', - MAX_CAMPAIGN_EXPENSES
'COD_SIT_TOT_TURNO', - ROUND_TOT_SIT_CODE
'DESC_SIT_TOT_TURNO', - ROUND_TOT_SIT_NAME
'NM_EMAIL', - NM_EMAIL
'TIPO_LEGENDA', - PARTY_LABEL_TYPE
'SIGLA_COLIGACAO', - COALITION_ABBREVIATION
'NOME_COLIGACAO',- COALITION_NAME
'COMPOSICAO_COLIGACAO',- COALITION_COMPOSITION
'SEQUENCIA_COLIGACAO', - COALITION_SEQUENTIAL
'CODIGO_MACRO', - MACRO_REGION_CODE
'NOME_MACRO', - MACRO_REGION_NAME
'UF', - FEDERATION_UNIT
'NOME_UF', FEDERATION_UNIT_NAME
'CODIGO_MESO', - MESO_REGION_CODE
'NOME_MESO', - MESO_REGION_NAME
'CODIGO_MICRO',- MICRO_REGION_CODE
'NOME_MICRO', - MICRO_REGION_NAME
'CODIGO_MUNICIPIO', - MUNICIPALITY_CODE
'NOME_MUNICIPIO', - MUNICIPALITY_NAME
'NUM_ZONA', - ELECTORAL_ZONE_NUMBER
'QTDE_VOTOS' - VOTES_AMOUNT
