### ISSUE TITLE
Incluir a UF quando for realizar o filtro por Município

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#20]
O Brasil possui mais de 5500 municípios e existem alguns municípios homônimos no país. Para evitar confusões e facilitar a usabilidade, seria importante incluir após o nome do município a UF (por ex: São Paulo - SP). Não existem dois municípios com o mesmo nome em uma mesma UF.

**Comment by laramesquita** [comment]
Pelo que entendi, além de adicionar a UF no nome precisamos rever o filtro. Ao começar digitar São Paulo, apareceram várias opções (são paulo do potengi; são paulo de olivença etc...); selecionei a opção "São Paulo", mas a primeira linha do resultado foi "SÃO PAULO DE OLIVENÇA" e a segunda foi "SÃO PAULO DO POTENGI", o que indica algum erro no filtro. A consulta também não funciona para todas as cidades. Tentei Vitória e São José dos Campos e não encontrou resultados. É porque ainda está carregando ou há algum erro?

**Comment by laramesquita** [comment]
![image](https://user-images.githubusercontent.com/29128843/26947240-64779cd0-4c68-11e7-9191-4d7639b0369e.png)
