### ISSUE TITLE
API não está funcionando com o domínio CEPESP.io

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#33]
Caros,

Estou utilizando o API para realizar alguns testes de consistências.
No entanto, ao utilizar o domínio CEPESP.Io, estou tendo problemas no momento de importar os dados.
Os dados não são puxados corretamente.

Quando utilizo o domínio http://ec2-54-233-155-151.sa-east-1.compute.amazonaws.com, funciona sem problemas.

**Comment by abraaobarros** [comment]
Agora está apontando para a http://api.cepesp.io
