### ISSUE TITLE
Consulta API sem detalhes do candidato

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#34]
Caros,
Estou realizando uma consulta simples ao API para verificar a quantidade de eleitos por eleição a fim de testar a consistência dos resultados. No entanto, para os resultados que vêm do API no R, não há vários detalhes da candidatura. 

Somente estas variáveis estão disponíveis:
> names(consulta3)
 [1] "SIGLA_PARTIDO"    "NUM_TURNO"        "DESCRICAO_CARGO"  "ANO_ELEICAO"      "NUMERO_PARTIDO"  
 [6] "NUMERO_CANDIDATO" "UF"               "NOME_UF"          "NOME_CANDIDATO"   "QTDE_VOTOS"

**Comment by abraaobarros** [comment]
Arthur, 
Para que você tenha acesso às outras colunas tem que enviar as colunas na requisição.

Voce pode fazer isso no R dessa forma:
colunas <- list("ANO_ELEICAO","UF","CODIGO_MUNICIPIO","NOME_MUNICIPIO","NOME_URNA_CANDIDATO","NUMERO_CANDIDATO","NUMERO_PARTIDO","SIGLA_PARTIDO","QTDE_VOTOS")
  names(colunas) <- rep("selected_columns[]",length(colunas))
  consulta <- append(list(anos ="2010",agregacao_regional=6,agregacao_politica=2,cargo=6),colunas)

**Comment by atrfisch** [comment]
obrigado
