### ISSUE TITLE
Problemas de Encoding dos nomes e observações duplicadas após download do CSV

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#35]
Caros
Estou verificando algumas informações do CEPESP.io e realizei a seguinte query:
Political office: deputado federal
Geographical aggregation: UF
Political Aggregation: Candidato
Year: 2010

Percebi que há valores de observações duplicadas e problemas no encoding como é possível ver abaixo:
![image](https://user-images.githubusercontent.com/11951620/27051370-359a17c2-4f8c-11e7-9c59-a922d312394e.png)

**Comment by abraaobarros** [comment]
Todos os Arquivos estão em utf-8. Qual o charset vc tá usando?

**Comment by abraaobarros** [comment]
além disso, está aparecendo duplicado por causa do SEQUENCIA_COLIGACAO. Aparentemente tem 3 legendas com mesmo nome mas com sequencia diferente...

**Comment by atrfisch** [comment]
Abraao
Acabamos de verificar, o TSE multiplicou os valores da coligação.
Assim, a mesma coligação aparece 3 vezes na base legenda e por isso está duplicada na nossa base.
