### ISSUE TITLE
  COMPOSICAO_COLIGACAO #NE#

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#36]
Nas eleições de 2006 e 2010 a  COMPOSICAO_COLIGACAO informa #NE# para todos os casos

**Comment by abraaobarros** [comment]
esse é um problema do Tse. Podemos fechar essa Issue?

**Comment by laramesquita** [comment]
@abraaobarros em conversa com o Avelino na semana passada, após ele conversar com o Felipe, do TSE, decidimos que vamos reconstruir as informações da composição das coligações para atualizar os anos em que o TSE não dá essa informação pronta. A ideia é seguir aquela rotina proposta pelo Arthur. Podemos conversar melhor na reunião de amanhã.
