### ISSUE TITLE
Deputados Distritais

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#38]
Criar agregação "Type of political office": **deputado distrital** e incluir no pacote R, uma função que permita juntas os resultados de "Deputados Distritais" com os "Deputados Estaduais";

**Comment by abraaobarros** [comment]
@laramesquita podemos fechar esse?

**Comment by laramesquita** [comment]
@abraaobarros pelo teste que fiz para 2014 estão apenas os votos de legenda (bate com o TSE). A consulta que fiz foi a seguinte: 
Type of political office: Deputado Estadual
Geographical aggregation: UF
Political aggregation: Partido
Year: 2014

**Comment by laramesquita** [comment]
@abraaobarros pelo teste que fiz para 2014 estão apenas os votos de legenda (bate com o TSE). A consulta que fiz foi a seguinte: 
Type of political office: Deputado Estadual
Geographical aggregation: UF
Political aggregation: Partido
Year: 2014

**Comment by laramesquita** [comment]
@abraaobarros para 2006, filtrando os deputados estaduais e o DF, retornam apenas os votos brancos e nulos, só duas linhas.

**Comment by laramesquita** [comment]
@abraaobarros para 2002 e 1998, filtrando os deputados estaduais e o DF, também retornam apenas os votos brancos e nulos, só duas linhas para cada ano.
