### ISSUE TITLE
duplicidade das coligações presidenciais

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#51]
Atualizar a quantidade de votos para presidente, que está duplicada de 2006 a 2014, como consequência da duplicação das coligações (mesma composição apresentada em ordem de partidos distintas). Não está duplicado no arquivo original do TSE.

**Comment by abraaobarros** [comment]
A mesma coligação está de duas formas diferentes...

PC do B / PDT / PMDB / PP / PR / PRB / PROS / PSD / PT
PT / PMDB / PSD / PP / PR / PROS / PDT / PC do B / PRB


[legendas_2014_presidente.csv.zip](https://github.com/Cepesp-Fgv/tse-dados/files/1242054/legendas_2014_presidente.csv.zip)

**Comment by abraaobarros** [comment]
Para corrigir essa anomalia, filtrei os presidentes da tabela consulta legendas. Pois esses dados já estão na tabela consulta_legenda_presidentes.

Os dados já estão no cepesp.io no 3 banco consulta legenda.
