### ISSUE TITLE
Atualizar informação de coligações para 1998. P/ governador, senador, deputado federal, estadual e distrital retorna #NE# e #NULO#;

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#55]
Atualizar informação de coligações para 1998. P/ governador, senador, deputado federal, estadual e distrital retorna #NE# e #NULO#;
a.     Ainda não atualizado. O arquivo do TSE segue a mesma estrutura (mesmo número, sequencia e conteúdo de colunas, separador ";") dos outros anos. O TSE não informa a composição da coligação no campo “COMPOSICAO_COLIGACAO” (17ª coluna). Informa #NE# e #NULO# no cado de “Partidos Isolados”. Passamos arquivo complementar, mas como cada partido da coligação é uma linha, e há o nome da coligação (o código “SEQUENCIAL_COLIGACAO” é -1 em todos os casos para 1998) que se repete para todos os partidos de uma mesma coligação, é possível recuperar a informação da composição da coligação.

**Comment by abraaobarros** [comment]
Fico no aguardo desse arquivo corrigido também.

[legendas_1998.csv.zip](https://github.com/Cepesp-Fgv/tse-dados/files/1242039/legendas_1998.csv.zip)

**Comment by abraaobarros** [comment]
Lara, tentei rodar o script que tínhamos criado para as eleições que não tinham o composição coligação preenchidos. Mas esse arquivo não possui sequencial coligação. Como proceder?

**Comment by laramesquita** [comment]
Abraao,

Nesse caso temos que reconstruir o sequencial das coligações com base nos nomes das coligações. (Sempre controlando por UF e cargo).

Se quiser podemos nos falar mais tarde.



Lara Mesquita
Cientista Política
http://lattes.cnpq.br/7180517519005425

**Comment by atrfisch** [comment]
Abraão e Lara

Eu e o Ivan trabalhamos em um código mais cedo esse ano, justamente para
resolver este problema das coligações de 1998. O problema é q ele está em
linguagem do stata.

Posso mandar hoje mais tarde a lógica por de trás dele. Acho que ajudará.

Abs
Arthur

Em 31 de ago de 2017 3:42 PM, "laramesquita" <notifications@github.com>
escreveu:

**Comment by abraaobarros** [comment]
Caros, 

Criei um algoritmo parecido com o outro utilizando como chave o nome da coligação e não o sequencial.

Verifiquem se tá ok no banco consulta_legenda no cepesp.io . se tiver ok, recalculo para o votacao_secao.

Caso queiram avaliar, o arquivo tratado é esse em anexo.

[legendas_1998.csv.gz](https://github.com/Cepesp-Fgv/tse-dados/files/1268660/legendas_1998.csv.gz)

**Comment by atrfisch** [comment]
@abraaobarros  e @laramesquita 

Terminei de rodar um teste para 98, a partir da api do cepesp.io, para ver se o número de coligações por uf entre a nossa plataforma e uma planilha de controle que a lara me enviou estavam batendo.

Para todos os cargos (governador, dep est, dep fed e senador) o número foi o mesmo.
