### ISSUE TITLE
Coligações - Dados de Partidos Isolados para Eleições de 2014

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#59]
@abraaobarros 

Após verificar os dados de coligação de 2014, não estavam na consulta que fiz via api as informações dos partidos isolados. Peço, por gentileza, para alterar.

O código que fiz a consulta foi:

#pacotes necessarios
library(httr)
library(dplyr)

#2014 

#coligacao governador
colunas <- list(
  "DATA_GERACAO",
  "HORA_GERACAO",
  "ANO_ELEICAO",
  "NUM_TURNO",
  "DESCRICAO_ELEICAO",
  "SIGLA_UF",
  "SIGLA_UE",
  "DESCRICAO_UE",
  "CODIGO_CARGO",
  "DESCRICAO_CARGO",
  "TIPO_LEGENDA",
  "NUMERO_PARTIDO",
  "SIGLA_PARTIDO",
  "NOME_PARTIDO",
  "SIGLA_COLIGACAO",
  "NOME_COLIGACAO",
  "COMPOSICAO_COLIGACAO",
  "SEQUENCIAL_COLIGACAO"
)
names(colunas) <- rep("selected_columns[]",length(colunas))
consulta <- append(list(anos ="2014", cargo=3),colunas)

resp <-GET("http://ec2-54-233-155-151.sa-east-1.compute.amazonaws.com/api/consulta/legendas", query= consulta)
colig_2014<- content(resp, type="text/csv")

#filtro por cargo

n_coligs_14 <- colig_2014 %>%
  group_by(SIGLA_UE, DESCRICAO_CARGO, TIPO_LEGENDA, NOME_COLIGACAO, COMPOSICAO_COLIGACAO, SEQUENCIAL_COLIGACAO, NUM_TURNO)%>%
  summarize(total=n())

#part_isol_14 <-n_coligs_14 %>%
#  filter(TIPO_LEGENDA=="PARTIDO_ISOLADO")

n_coligs_14 <- n_coligs_14 %>%
  filter(NUM_TURNO==1)%>%
  group_by(SIGLA_UE, DESCRICAO_CARGO)%>%
  summarize(total=n())

#n_coligs_14 <- merge(x= n_coligs_14, y=part_isol_14, by="SIGLA_UE")
#n_coligs_14$total <- n_coligs_14$total.x + n_coligs_14$total.y 

#n_coligs_14 <- n_coligs_14 %>%
#  select(SIGLA_UE, DESCRICAO_CARGO.x, total)

#2010 

#coligacao governador
colunas <- list(
  "DATA_GERACAO",
  "HORA_GERACAO",
  "ANO_ELEICAO",
  "NUM_TURNO",
  "DESCRICAO_ELEICAO",
  "SIGLA_UF",
  "SIGLA_UE",
  "DESCRICAO_UE",
  "CODIGO_CARGO",
  "DESCRICAO_CARGO",
  "TIPO_LEGENDA",
  "NUMERO_PARTIDO",
  "SIGLA_PARTIDO",
  "NOME_PARTIDO",
  "SIGLA_COLIGACAO",
  "NOME_COLIGACAO",
  "COMPOSICAO_COLIGACAO",
  "SEQUENCIAL_COLIGACAO"
)
names(colunas) <- rep("selected_columns[]",length(colunas))
consulta <- append(list(anos ="2010", cargo=3),colunas)

resp <-GET("http://ec2-54-233-155-151.sa-east-1.compute.amazonaws.com/api/consulta/legendas", query= consulta)
colig_2010<- content(resp, type="text/csv")

#filtro por cargo

n_coligs_10 <- colig_2010 %>%
  group_by(SIGLA_UE, DESCRICAO_CARGO, TIPO_LEGENDA, NOME_COLIGACAO, COMPOSICAO_COLIGACAO, SEQUENCIAL_COLIGACAO, NUM_TURNO)%>%
  summarize(total=n())

part_isol_10 <-n_coligs_10 %>%
  filter(NUM_TURNO==1 & TIPO_LEGENDA=="PARTIDO ISOLADO")

**Comment by abraaobarros** [comment]
Caro @atrfisch,

Rodei o script para contar partidos isolados em todos os anos e encontrei isso:

1998  - Quantidade de partidos isolados: 0
2000  - Quantidade de partidos isolados: 0
2002  - Quantidade de partidos isolados: 0
2004  - Quantidade de partidos isolados: 14317
2006  - Quantidade de partidos isolados: 939
2008  - Quantidade de partidos isolados: 10965
2010  - Quantidade de partidos isolados: 776
2012  - Quantidade de partidos isolados: 11311
2014  - Quantidade de partidos isolados: 0
2016  - Quantidade de partidos isolados: 10987

Será que temos que reconstruir esses arquivos?
ou apenas desconsiderar quando esses dados forem nulos?(O LEFT JOIN faz isso)

**Comment by abraaobarros** [comment]
Os candidatos de 2014 em partidos isolados podem ser vistos na coluna nome coligação da tabela candidatos. Talvez o TSE tenha esquecido de colocar essas informaçãos na tabela legendas

![captura de tela 2017-09-06 as 13 56 28](https://user-images.githubusercontent.com/1097909/30124348-40b30fe8-930b-11e7-8cb4-4451cad33fe4.png)

**Comment by atrfisch** [comment]
@abraaobarros 

Acabei de analisar os arquivos originais do TSE e vc tem razão. O tribunal não incluiu os partidos isolados no banco de legendas, mas eles aparecem no banco de candidatos.

Não sei se vale a pena recolocar nesta consulta os partidos isolados, ou deixar para quando juntarmos as informações de candidatos quando isso deve ser resolver. Vou conversar com o pessoal.

**Comment by atrfisch** [comment]
Lara, como acha que devemos proceder nesse caso?

Na consulta geral, ficaria correto, pois quando juntarmos com a base de candidatos esse problema, ao menos teoricamente, sumiria. Mas a nova consulta de legendas (que eu achei uma adição boa para o cepespdata) ficaria incompleta.

**Comment by abraaobarros** [comment]
Agrupei as informações no formato da legenda dos candidatos de 2014.
Podem conferir, se tiver ok. Posso adicionar esses dados ao legendas.

[partidos_isolados_2014.csv.zip](https://github.com/Cepesp-Fgv/tse-dados/files/1282212/partidos_isolados_2014.csv.zip)

**Comment by abraaobarros** [comment]
apliquei esse algoritmo para outros anos e obtive a seguinte quantidade:
1998 - Numero partidos isolados: 0
2000 - Numero partidos isolados: 0
2002 - Numero partidos isolados: 0
2004 - Numero partidos isolados: 0
2006 - Numero partidos isolados: 0
2008 - Numero partidos isolados: 0
2010 - Numero partidos isolados: 0
2012 - Numero partidos isolados: 9572
2014 - Numero partidos isolados: 705
2016 - Numero partidos isolados: 10229

Os arquivos agrupados são:
[legendas_2012.csv.zip](https://github.com/Cepesp-Fgv/tse-dados/files/1282722/legendas_2012.csv.zip)
[legendas_2014.csv.zip](https://github.com/Cepesp-Fgv/tse-dados/files/1282724/legendas_2014.csv.zip)
[legendas_2016.csv.zip](https://github.com/Cepesp-Fgv/tse-dados/files/1282723/legendas_2016.csv.zip)

**Comment by atrfisch** [comment]
Acabei de conferir 2014, e para a grande maioria dos casos, está tudo certo.

Há algumas inconsistências, para determinados estados. Fui atrás do que possivelmente estivesse gerando as anomalias e as falhas são todas provenientes do TSE que classificou errado a coligação.

2 foram as principais fontes de problema:
- o Partido concorreu isoladamente, mas foi categorizado como coligação
- o Partido aparece como isolado, mas fez parte de coligação

Os casos foram:
![image](https://user-images.githubusercontent.com/11951620/30412523-754a3a90-98ee-11e7-9ea4-bee2f75ac3a9.png)

Acho que podemos prosseguir, pois a lógica me parece correta e consistente
