### ISSUE TITLE
Coligações - Composição partidos isolados

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#60]
@abraaobarros , 

Na nova consulta de coligações, quando a legenda é um partido isolado, a composição dele está aparecendo como #NE#, exatamente como vem do TSE. Seria interessante para deixar a consulta mais intuitiva e melhor, replicar a sigla do partido (ex: PT, PSDB, etc) nesse caso do que deixar #NE#. O que acha?

**Comment by abraaobarros** [comment]
Com os arquivos tratados, analisando ano a ano temos a coluna COMPOSICAO_COLIGACAO com esse perfil:

1998 - 369 Campos #NE#; 0 Partidos isolados ; 2638 legendas
2000 - 0 Campos #NE#; 0 Partidos isolados ; 17734 legendas
2002 - 0 Campos #NE#; 0 Partidos isolados ; 4842 legendas
2004 - 0 Campos #NE#; 14317 Partidos isolados ; 174308 legendas
2006 - 0 Campos #NE#; 939 Partidos isolados ; 4820 legendas
2008 - 186057 Campos #NE#; 10965 Partidos isolados ; 197022 legendas
2010 - 0 Campos #NE#; 776 Partidos isolados ; 6245 legendas
2012 - 0 Campos #NE#; 11311 Partidos isolados ; 229375 legendas
2014 - 0 Campos #NE#; 0 Partidos isolados ; 4942 legendas
2016 - 0 Campos #NE#; 10987 Partidos isolados ; 249475 legendas

Caso mais grave é o de 2008 onde tem mais campos nulos do que partidos isolados.

O resultado do mesmo script para os arquivos originais do Tse temos:
1998 - 369 Campos #NE#; 0 Partidos isolados ; 2638 legendas
2000 - 0 Campos #NE#; 0 Partidos isolados ; 17734 legendas
2002 - 0 Campos #NE#; 0 Partidos isolados ; 4842 legendas
2004 - 14317 Campos #NE#; 14317 Partidos isolados ; 174308 legendas
2006 - 939 Campos #NE#; 939 Partidos isolados ; 4820 legendas
2008 - 197022 Campos #NE#; 10965 Partidos isolados ; 197022 legendas
2010 - 776 Campos #NE#; 776 Partidos isolados ; 6245 legendas
2012 - 11311 Campos #NE#; 11311 Partidos isolados ; 229375 legendas
2014 - 0 Campos #NE#; 0 Partidos isolados ; 4966 legendas
2016 - 0 Campos #NE#; 10987 Partidos isolados ; 249475 legendas
