### ISSUE TITLE
[Consultar  Candidatos] Vários candidatos com o mesmo número

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/tse-dados#66]
![5551255173988352](https://user-images.githubusercontent.com/11080400/30642782-94c78b22-9de2-11e7-883f-fbf37c06d8f5.png)

**Comment by Cepesp-Fgv** [comment]
Estes candidatos possuem de fato o mesmo número, no entanto eles concorreram em distritos eleitorais diferentes. Se você adicionar na consulta as informações de sigla_uf (estado) e sigla_ue (unidade eleitoral) poderá verificar isto. É normal ter candidatos com mesmo número em regiões diferentes.
