### ISSUE TITLE
Atualizar a versão "CONSULTAR CANDIDATOS" para o último arquivo que o Arthur enviou

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#78]
Abraao, ao testar os deputados estaduais eleitos  na aba "CONSULTAR CANDIDATOS" identifiquei duas inconsistências: faltam 3 candidatos no AP em 2010 (2 do PTB/14 e 1 do PSDC/27) e um candidato no RJ em 2014 (PTB/14).

Esses erros estão corrigidos na última versão do arquivo de candidatos que o Arthur te passou, conferimos o arquivo, mas essa consulta não foi atualizada.

É fundamental que essa atualização seja feita o quanto antes, para que os concorrentes do desafio não trabalhem com a versão errada do banco.

**Comment by atrfisch** [comment]
@abraaobarros  o link do arquivo está aqui: https://fgv-urbbox.slack.com/files/U54A708DT/F78H0E6V8/candidatos_v2_corrigido.zip

Qualquer coisa me fala. Abs
arthur
