### ISSUE TITLE
Incluir a Agregação voto_seção nas consultas via API

### ISSUE THREAD

**Issue by atrfisch** [Cepesp-Fgv/tse-dados#80]
@abraaobarros 

Dadas as demandas de grupos interessados no challenge, solicitamos a inclusão da agregação voto_seção nas consultas de resultados da API. Tanto para a consulta Eleições por cargo quanto para a consulta Votação Seção.

**Comment by Cepesp-Fgv** [comment]
A agregação regional Votação Seção foi adicionada ao sistema.
