### ISSUE TITLE
interface de pesquisa usuário (http://cepesp.io/consulta/tse) retorna número de partido errado

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#81]
na interface de pesquisa com usuário `http://cepesp.io/consulta/tse` as pesquisas vem retornando número de partido errado. 

**Exemplo**: 

+ PESQUISA: `http://cepesp.io/consulta/tse?cargo=1&agregacao_regional=2&agregacao_politica=2&anos%5B%5D=2014&uf_filter=&mun_filter=`
+ RESULTADO: <http://www.inf.ufg.br/~ricardo/temp/issue-cepespdata.png>

na interface REST, ao menos, o número de partido está **correto**. Portanto, o erro não afeta o desenvolvimento das aplicações.

**Comment by Cepesp-Fgv** [comment]
Falha corrigida. O problema encontrava-se somente nas consultas para presidente.
