### ISSUE TITLE
Dados duplicados de governador na categoria Candidatos

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/tse-dados#83]
![captura de tela de 2017-11-02 14-28-27](https://user-images.githubusercontent.com/11080400/32337821-2ef21b5e-bfda-11e7-8967-64563e785b5f.png)

**Comment by laramesquita** [comment]
Caro Fredpolicarpo, obrigada. 
Na verdade a informação não está duplicada. Se você for em "adicionar coluna" e adicionar o campo "DESCRICAO_ELEICAO" verá que uma linha se refere as "Eleições Gerais 2014" e outra a "Eleição Suplementar Governador AM".  
Todavia entendemos que essa informação pode gerar confusão e vamos pensar a melhor maneira de apresentá-la, a fim de evitar erros. 
Att.
Equipe CepespData
