### ISSUE TITLE
Candidato eleito no 1o e 2 truno??

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/tse-dados#84]
Para o cenário abaixo, o valor correto para a coluna **desc_sit_tot_turno** no primeiro turno não deveria ser **2o Truno**??

![image](https://user-images.githubusercontent.com/11080400/32338738-c90b0d48-bfdc-11e7-908c-8884e5855fde.png)

**Comment by laramesquita** [comment]
Prezado fredpolicarpo, obrigada!

Você está correto, a informação deveria ser 2º Turno. Essa informação veio informada incorretamente (eleito nos dois turnos) no banco original do TSE, que está disponível  no repositório de dados eleitorais. 

Att.
Equipe CEPESPData
