### ISSUE TITLE
Documentação da interface REST incompleta e limitando o seu uso

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#85]
A [documentação da interface REST](https://github.com/Cepesp-Fgv/cepesp-rest/blob/master/EleicoesPorCargo.md) para consulta de votações está **incompleta**, não dispondo de nenhuma informação sobre como filtrar as consultas (exemplo: votos pelo estado de SP).

Essa funcionalidade está disponível, no mínimo, na API python que precisei consultar para realizar uma pesquisa desejada.

Essa falta de informação cria grandes entraves para a programação utilizando REST.

## Exemplo

Consegui fazer uma consulta, depois de inspecionar a API python, filtrando os resultados por estado usando a seguinte consulta:

`curl -i -g -X GET "http://cepesp.io/api/consulta/votos?ano=2014&cargo=1&agregacao_regional=2&selected_columns[]="NUM_TURNO"&selected_columns[]="NOME_MACRO"&selected_columns[]="DESCRICAO_CARGO"&selected_columns[]="QTDE_VOTOS"&selected_columns[]="UF"&columns[0][name]="UF"&columns[0][search][value]="ES""`

Não há informação na documentação para o uso da construção `&columns[0][name]="UF"&columns[0][search][value]="ES"`.

## Workarounds

1. Usar outra API ( inviável no meu caso )
2. Construir a documentação própria a partir do código da API python.

**Comment by Cepesp-Fgv** [comment]
Caro, 

Agradeço a sugestão, vamos atualizar a Documentação assim que possível.

atenciosamente

**Comment by rcarocha** [comment]
sugiro, por enquanto, deixar um link na documentação para esta issue.

**Comment by Cepesp-Fgv** [comment]
@rcarocha, adicionamos a documentação para os filtros. Segue o link:
https://github.com/Cepesp-Fgv/cepesp-rest/blob/master/Filtros.md
