### ISSUE TITLE
Interface pára de responder ao remover a coluna código do cargo.

### ISSUE THREAD

**Issue by josircg** [Cepesp-Fgv/tse-dados#88]
http://cepesp.io/consulta/candidatos?cargo=6&agregacao_regional=&agregacao_politica=&anos=2010&mun_filter=&uf_filter=&selected_columns%5B%5D=ANO_ELEICAO&selected_columns%5B%5D=SIGLA_UF&selected_columns%5B%5D=SIGLA_UE&selected_columns%5B%5D=SIGLA_PARTIDO&selected_columns%5B%5D=NOME_CANDIDATO&selected_columns%5B%5D=NUMERO_CANDIDATO

Não sei se a issue deve ser registrada aqui nesse repo já que não achei os códigos fontes da interface visual aqui.

**Comment by Cepesp-Fgv** [comment]
Não será mais necessário implementar uma interface que proíba a remoção da coluna CODIGO_CARGO. Agora, colunas filtradas não precisar estar necessariamente listadas no resultado final do processamento. Deste modo, o link informado agora é uma consulta válida.
