### ISSUE TITLE
Excluir eleições suplementares das eleições gerais (AM - 2014)

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#89]
Vamos seguir o padrão adotado para as disputas municipais e informar separadamente as eleições suplementares das eleições ordinárias.

Nas eleições gerais (1998, 2002, 2006, 2010 e 2014) só temos um caso de eleição suplementar, que foi para governador no AM. A eleição ocorreu em 2017 em substituição do pleito de 2014.

A "DESCRICAO_ELEICAO" que identifica as eleições ordinárias, as que queremos manter, são:
ELEICOES 1998
ELEICOES 2002
ELEICOES 2006
ELEIÇÕES 2010
Eleições Gerais 2014

A "DESCRICAO_ELEICAO" que identifica a eleição suplementar que precisa ser excluída é:
Eleição Suplementar Governador AM

**Comment by elianalins** [comment]
Fiz a consulta novamente para cargo = Governador, anos = 2014 a 2018, agregação política = Candidato, filtrando p/ UF=AM e Descrição Eleição = "Eleição Suplementar Governador AM" e obtive 0 resultado. Acredito que este issue esteja resolvido.
