### ISSUE TITLE
deafult e ordenação das colunas na aba "consultar candidatos"

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#90]
As colunas devem aparecer na seguinte sequencia:

ANO_ELEICAO
NUM_TURNO 
DESCRICAO_ELEICAO 
SIGLA_UF 
SIGLA_UE 
CODIGO_CARGO
NUMERO_PARTIDO
SIGLA_PARTIDO
NUMERO_CANDIDATO
DES_SITUACAO_CANDIDATURA
DESC_SIT_TOT_TURNO

A ordenação deve ser por Ano, UF, UE, CODIGO_CARGO e NUMERO_CANDIDATO.
Essa ordenação vale para todas as consultas possíveis nos CEPESPData.

**Comment by Cepesp-Fgv** [comment]
Correções feitas.
