### ISSUE TITLE
Deafult e ordenação "CONSULTAR LEGENDAS"

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#91]
As colunas devem aparecer na seguinte sequencia:
ANO_ELEICAO
NUM_TURNO
SIGLA_UF
SIGLA_UE
CODIGO_CARGO
NUMERO_PARTIDO
SIGLA_PARTIDO
COMPOSICAO_COLIGACAO
TIPO_LEGENDA

A ordenação deve ser por Ano, UF, UE, CODIGO_CARGO e NUMERO_PARTIDO.

**Comment by Cepesp-Fgv** [comment]
Correções feitas.
