### ISSUE TITLE
Atualizar descrição do que faz a aba "Votação Seção"

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#93]
Atualizar as informações da aba "Votação Seção". Ao clicar na Aba o nome é o mesmo da aba "Eleições por Cargo", o que gera confusão para o usuário. Sugestão de nome:

Resultado da Eleição. O nome da aba também poderia ser esse.

Texto da descrição:
Este formulário permite efetuar consultas aos resultados eleitorais especificando um cargo eletivo. As consultas podem ser também agregadas por nível regional.

**Comment by Cepesp-Fgv** [comment]
Texto alterado @laramesquita, mas vamos precisar desta mesma descrição em inglês também.

**Comment by laramesquita** [comment]
This form allows you to search the election results by specifying an elective position. Searchs can also be aggregated at the regional level.
