### ISSUE TITLE
Default e ordenação "Votação Seção"

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#94]
As colunas devem aparecer na seguinte sequencia:

DESCRICAO_ELEICAO
ANO_ELEICAO
NUM_TURNO
SIGLA_UF
SIGLA_UE
NOME_MUNICIPIO
CODIGO_CARGO
NUMERO_CANDIDATO
QTDE_VOTOS

Seria importante incluir aqui o código no município do IBGE como opção. Aparece duas vezes o código do TSE (SIGLA_UE e COD_MUN_TSE)

A ordenação deve ser por Ano, UF, UE, CODIGO_CARGO e NUMERO_CANDIDATO.
Essa ordenação vale para todas as consultas possíveis nos CEPESPData.

**Comment by Cepesp-Fgv** [comment]
Done.
