### ISSUE TITLE
dados faltantes na consulta votação seção presidente 2014 e 2006

### ISSUE THREAD

**Issue by nataliabueno** [Cepesp-Fgv/tse-dados#95]
A consulta Cargo (Presidente), Agregação Regional (Votação Seção), Ano (2014), UF (AC -- tentei com outras UFs também) não gera uma tabela. O retorno é "No data available in table"

O problema só acontece em 2014 e 2006, ele aparentemente não acontece com 2010, 2002 e 1998.

**Comment by Cepesp-Fgv** [comment]
Problema resolvido.
