### ISSUE TITLE
interface CEPESPData (usuário) não pesquisa corretamente com caracteres acentuados

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#96]
A interface de pesquisa [CEPESPData](http://cepesp.io/) não utiliza a codificação de caracteres correta na interface de pesquisa em relação ao dado mantido no banco de dados, fazendo com que filtragens de pesquisa com texto acentuado não funcione.

* **Exemplo**: [Pesquisa por resultado para presidente](http://cepesp.io/consulta/tse?cargo=1&agregacao_regional=6&agregacao_politica=2&anos%5B%5D=2014&uf_filter=ES&mun_filter=) em 2014, agregado por município e filtrado pelo estado "ES"
   * Ao filltrar o município por *"Vitória"* o resultado é vazio devido ao problema na acentuação. Pesquisando por *"Vit"* o município *"Vitória"* aparece corretamente.

**Comment by Cepesp-Fgv** [comment]
Existe um problema com a acentuação de caracteres no que se refere a sensibilidade de caixa alta ou caixa baixa. No caso é específico, a consulta só funciona quando o caractere "Ó" é especificado em caixa alta de acordo com como está apresentado na tabela. Nos outros caracteres que não possuem acentuação, o fato de estarem em maiúsculo ou minúsculo não muda o resultado
