### ISSUE TITLE
default Resultado da Eleição por seção eleitoral

### ISSUE THREAD

**Issue by laramesquita** [Cepesp-Fgv/tse-dados#98]
Na pesquisa "Resultado da Eleição", na agregação "seção eleitoral" os seguintes campos, na sequencia indicada abaixo debem retornar automaticamente:

ANO_ELEICAO 
NUM_TURNO
DESCRICAO_ELEICAO
UF
SIGLA_UE
COD_MUN_TSE
NUM_ZONA
NUM_SECAO
CODIGO_CARGO
NUMERO_CANDIDATO
QTDE_VOTOS

**Comment by Cepesp-Fgv** [comment]
Colunas padrões alteradas.
