### ISSUE TITLE
Falta de documentação em pesquisas REST para agregação política (API REST)

### ISSUE THREAD

**Issue by rcarocha** [Cepesp-Fgv/tse-dados#99]
A pesquisas REST de "Resultados das Eleições por Cargo", não documenta como realizar uma pesquisa com agregação política (`agregacao_politica`).

Observe que a indicação **API REST** na issue não necessariamente restringue o problema à API REST.

**Comment by elianalins** [comment]
Boa noite, @rcarocha . Houve algumas alterações no site do Cepespdata nos últimos meses. É possível indicar na consulta via API Rest qual a agregação política desejada, no local apropriado dentro do link. Por exemplo, a consulta a cargo = Presidente, agregação regional = Brasil, e agregação política = Candidato corresponde ao seguinte url:

`http://cepespdata.io/consulta/tse?cargo=1&agregacao_regional=0&agregacao_politica=2&anos%5B%5D=2018&uf_filter=&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS`.

Ao substituir no link acima o trecho `agregacao_politica=2` pelo código da agregação política desejada, você consegue alterar a consulta. Os códigos são os seguintes:

1 - Partido
2 - Candidato
3 - Coligação
4 - Consolidado da Eleição 

De toda forma, agradecemos o feedback e vamos trabalhar para melhorar a nossa documentação de API Rest. 

Sempre à disposição, Equipe Cepespdata
